modules_debug = [
                 "ttt",
                 ]

modules =  ["makeSD",
            "CaloClusterFast",
            #"CaloHitMaker",
            "CaloHitMakerFast",
            "aprLowPStopTargHSFilter",
            "aprLowPStopTargPS",
            "aprLowPStopTargTCFilter",
            "aprLowPStopTargKSFilter",
            "aprHighPStopTargHSFilter",
            "aprHighPStopTargPS",
            "aprHighPStopTargTCFilter",
            "aprHighPStopTargKSFilter",
            "cprDeLowPStopTargHSFilter",
            "cprDeLowPStopTargPS",
            "cprDeLowPStopTargTCFilter",
            "cprDeLowPStopTargKSFilter",
            "cprDeHighPStopTargHSFilter",
            "cprDeHighPStopTargPS",
            "cprDeHighPStopTargTCFilter",
            "cprDeHighPStopTargKSFilter",
            #"OfflineFragmentReader",
            # "tprHelixDeIpaPhiScaledHSFilter",
            # "tprHelixDeIpaPhiScaledPS",
            # "tprHelixDeIpaPhiScaledTCFilter",
            # "tprHelixDeIpaHSFilter",
            # "tprHelixDeIpaPS",
            # "tprHelixDeIpaTCFilter",
            # "tprDeLowPStopTargHSFilter",
            # "tprDeLowPStopTargPS",
            # "tprDeLowPStopTargTCFilter",
            # "tprDeLowPStopTargKSFilter",
            # "tprDeHighPStopTargHSFilter",
            # "tprDeHighPStopTargPS",
            # "tprDeHighPStopTargTCFilter",
            # "tprDeHighPStopTargKSFilter",
            "TTCalHelixFinderDe",
            "TTCalHelixMergerDe",
            "TTCalSeedFitDe",
            "TTCalTimePeakFinder",
            "TTflagBkgHits",
            "TTDeltaFinder",
            #"TThelixFinder",
            #"TTHelixMergerDe",
            #"TTKSFDe",
            "TTTZClusterFinder",
            "TTAprHelixFinder",
            "TTAprHelixMerger",
            "TTAprKSF",
            "TTmakeSH",
            "TTmakePH",
            "TTmakeSTH",
            #"TTtimeClusterFinder"
            ]
